import crypto from "node:crypto";
import { Difficulty, PrismaClient, QuestionStatus, QuestionType } from "@prisma/client";
const db = new PrismaClient();
type Seed = { year: number; category: string; subcategory: string; difficulty: Difficulty; question: string; options: string[]; answer: string; explanation: string; source: string; type?: QuestionType };
const seeds: Seed[] = [
  { year: 2000, category: "Sports", subcategory: "Olympics", difficulty: "HARD", question: "Which Nigerian weightlifter won silver at the Sydney 2000 Olympics?", options: ["Ruth Ogbeifo", "Chioma Ajunwa", "Blessing Okagbare", "Mary Onyali"], answer: "Ruth Ogbeifo", explanation: "Ruth Ogbeifo won silver for Nigeria in the women's 75 kg weightlifting event at Sydney 2000.", source: "https://olympics.com/en/athletes/ruth-ogbeifo" },
  { year: 2001, category: "Technology", subcategory: "Telecoms", difficulty: "EASY", question: "Which telecom network made its first Nigerian call in May 2001?", options: ["MTN", "Etisalat", "Glo", "Starcomms"], answer: "MTN", explanation: "MTN records May 2001 as the date of its first call in Nigeria.", source: "https://www.mtn.com/about-us/" },
  { year: 2002, category: "Sports", subcategory: "World Cup", difficulty: "MEDIUM", question: "Which team did Nigeria hold to a goalless draw at the 2002 World Cup?", options: ["England", "Argentina", "Sweden", "Senegal"], answer: "England", explanation: "Nigeria and England drew 0–0 in Osaka in their final Group F match.", source: "https://www.fifa.com/tournaments/mens/worldcup/2002korea-japan/match-center" },
  { year: 2003, category: "Nollywood", subcategory: "Movies", difficulty: "EASY", question: "Who played the title character in the 2003 comedy Osuofia in London?", options: ["Nkem Owoh", "John Okafor", "Victor Osuagwu", "Sam Loco Efe"], answer: "Nkem Owoh", explanation: "Nkem Owoh starred as Osuofia in the 2003 Nollywood comedy.", source: "https://www.imdb.com/title/tt0451109/" },
  { year: 2004, category: "Music", subcategory: "Songs", difficulty: "EASY", question: "Which artist released African Queen on the 2004 album Face 2 Face?", options: ["2Baba", "D'banj", "Ruggedman", "Styl-Plus"], answer: "2Baba", explanation: "African Queen appears on 2Baba's debut solo album Face 2 Face.", source: "https://music.apple.com/ng/album/face-2-face/322009801" },
  { year: 2005, category: "Music", subcategory: "Albums", difficulty: "EASY", question: "Which duo released the album Get Squared in 2005?", options: ["P-Square", "Bracket", "Danfo Drivers", "Plantashun Boiz"], answer: "P-Square", explanation: "Get Squared was P-Square's second studio album.", source: "https://music.apple.com/ng/album/get-squared/299246214" },
  { year: 2006, category: "Television", subcategory: "Reality TV", difficulty: "MEDIUM", question: "Who won the first Big Brother Nigeria edition in 2006?", options: ["Katung Aduwak", "Ebuka Obi-Uchendu", "Gideon Okeke", "Efe Ejeba"], answer: "Katung Aduwak", explanation: "Katung Aduwak won the original 2006 Big Brother Nigeria season.", source: "https://www.dstv.com/africamagic/en-ng/show/big-brother-naija" },
  { year: 2007, category: "Music", subcategory: "Songs", difficulty: "EASY", question: "Who released the 2007 hit Yahooze?", options: ["Olu Maintain", "9ice", "D'banj", "Wande Coal"], answer: "Olu Maintain", explanation: "Yahooze became Olu Maintain's defining 2007 solo hit.", source: "https://music.apple.com/ng/album/yahooze/319590352" },
  { year: 2008, category: "Music", subcategory: "Albums", difficulty: "EASY", question: "Gongo Aso was a major 2008 album by which Nigerian artist?", options: ["9ice", "MI Abaga", "Timaya", "Banky W"], answer: "9ice", explanation: "9ice released the album Gongo Aso in 2008.", source: "https://music.apple.com/ng/album/gongo-aso/292578070" },
  { year: 2009, category: "Music", subcategory: "Collaborations", difficulty: "HARD", question: "Which anti-cybercrime song brought several Nigerian stars together in 2009?", options: ["Maga No Need Pay", "One Love", "Great Nation", "Stand Up Nigeria"], answer: "Maga No Need Pay", explanation: "Maga No Need Pay was released through the Microsoft-backed Internet Safety, Security and Privacy Initiative for Nigeria.", source: "https://news.microsoft.com/2009/10/29/microsoft-and-nigerian-artists-collaborate-to-fight-cybercrime/" },
  { year: 2010, category: "Sports", subcategory: "World Cup", difficulty: "MEDIUM", question: "Who captained Nigeria at the 2010 FIFA World Cup?", options: ["Joseph Yobo", "Nwankwo Kanu", "Vincent Enyeama", "John Obi Mikel"], answer: "Joseph Yobo", explanation: "Joseph Yobo captained the Super Eagles at South Africa 2010.", source: "https://www.fifa.com/tournaments/mens/worldcup/2010south-africa/teams/43876" },
  { year: 2011, category: "Music", subcategory: "Albums", difficulty: "EASY", question: "Which artist released the debut album Superstar in 2011?", options: ["Wizkid", "Davido", "Olamide", "Ice Prince"], answer: "Wizkid", explanation: "Wizkid released Superstar as his debut studio album in June 2011.", source: "https://music.apple.com/ng/album/superstar/451811733" },
  { year: 2012, category: "Music", subcategory: "Songs", difficulty: "MEDIUM", question: "Which Nigerian artist took Oliver Twist into the UK Singles Chart top ten in 2012?", options: ["D'banj", "Wizkid", "Iyanya", "Davido"], answer: "D'banj", explanation: "D'banj's Oliver Twist reached number nine on the UK Singles Chart.", source: "https://www.officialcharts.com/songs/dbanj-oliver-twist/" },
  { year: 2013, category: "Sports", subcategory: "AFCON", difficulty: "EASY", question: "Who scored Nigeria's winning goal in the 2013 AFCON final?", options: ["Sunday Mba", "Victor Moses", "Ahmed Musa", "Emmanuel Emenike"], answer: "Sunday Mba", explanation: "Sunday Mba scored the only goal as Nigeria beat Burkina Faso in the final.", source: "https://www.cafonline.com/caf-africa-cup-of-nations/news/nigeria-crowned-african-champions/" },
  { year: 2014, category: "Sports", subcategory: "World Cup", difficulty: "EASY", question: "Which country knocked Nigeria out in the Round of 16 at the 2014 World Cup?", options: ["France", "Germany", "Argentina", "Netherlands"], answer: "France", explanation: "France defeated Nigeria 2–0 in Brasília in the Round of 16.", source: "https://www.fifa.com/tournaments/mens/worldcup/2014brazil/match-center" },
  { year: 2015, category: "History", subcategory: "Elections", difficulty: "EASY", question: "Who won Nigeria's 2015 presidential election?", options: ["Muhammadu Buhari", "Goodluck Jonathan", "Atiku Abubakar", "Olusegun Obasanjo"], answer: "Muhammadu Buhari", explanation: "INEC declared Muhammadu Buhari winner of the 2015 presidential election.", source: "https://www.inecnigeria.org/?page_id=31" },
  { year: 2016, category: "Sports", subcategory: "Olympics", difficulty: "MEDIUM", question: "Which medal did Nigeria's men's football team win at Rio 2016?", options: ["Bronze", "Gold", "Silver", "No medal"], answer: "Bronze", explanation: "Nigeria defeated Honduras in the bronze-medal match.", source: "https://olympics.com/en/olympic-games/rio-2016/results/football/football-men" },
  { year: 2017, category: "Television", subcategory: "Reality TV", difficulty: "EASY", question: "Who won BBNaija's See Gobe season in 2017?", options: ["Efe", "Bisola", "Tboss", "ThinTallTony"], answer: "Efe", explanation: "Efe Ejeba won the 2017 See Gobe edition.", source: "https://www.dstv.com/africamagic/en-ng/show/big-brother-naija" },
  { year: 2018, category: "Fashion", subcategory: "Football kits", difficulty: "EASY", question: "Which sportswear company designed Nigeria's famous 2018 World Cup kit?", options: ["Nike", "Adidas", "Puma", "Umbro"], answer: "Nike", explanation: "Nike designed the widely celebrated 2018 Nigeria national-team collection.", source: "https://news.nike.com/news/nigeria-national-team-collection-2018" },
  { year: 2019, category: "Music", subcategory: "Albums", difficulty: "EASY", question: "Which Burna Boy album was nominated at the 2020 Grammys?", options: ["African Giant", "Twice As Tall", "Outside", "Love, Damini"], answer: "African Giant", explanation: "African Giant earned Burna Boy his first Grammy nomination.", source: "https://www.grammy.com/artists/burna-boy/251682" },
  { year: 2020, category: "Television", subcategory: "Reality TV", difficulty: "EASY", question: "Who won the BBNaija Lockdown season in 2020?", options: ["Laycon", "Dorathy", "Nengi", "Ozo"], answer: "Laycon", explanation: "Laycon won the fifth BBNaija season, themed Lockdown.", source: "https://www.dstv.com/africamagic/en-ng/show/big-brother-naija" },
  { year: 2021, category: "Music", subcategory: "Awards", difficulty: "EASY", question: "Which album earned Burna Boy his first Grammy win in 2021?", options: ["Twice As Tall", "African Giant", "Love, Damini", "Outside"], answer: "Twice As Tall", explanation: "Twice As Tall won Best Global Music Album at the 63rd Grammys.", source: "https://www.grammy.com/news/burna-boy-wins-best-global-music-album-twice-tall-2021-grammy-awards-show/" },
  { year: 2022, category: "Music", subcategory: "Albums", difficulty: "MEDIUM", question: "Which Burna Boy album released in July 2022 includes Last Last?", options: ["Love, Damini", "I Told Them…", "Twice As Tall", "African Giant"], answer: "Love, Damini", explanation: "Love, Damini was released in July 2022 and includes Last Last.", source: "https://www.grammy.com/news/5-takeaways-burna-boy-love-damini-new-album/" },
  { year: 2023, category: "Internet Culture", subcategory: "Viral moments", difficulty: "EASY", question: "Which Nigerian chef's cooking marathon became a massive national moment in 2023?", options: ["Hilda Baci", "Tolu Eros", "Fregz", "Gina Ehikodi"], answer: "Hilda Baci", explanation: "Hilda Baci's Lagos cooking marathon became a viral event and was officially recognised by Guinness World Records.", source: "https://www.guinnessworldrecords.com/news/2023/6/hilda-baci-awarded-record-for-worlds-longest-cooking-marathon-753838" },
  { year: 2024, category: "Sports", subcategory: "Football", difficulty: "EASY", question: "Which Nigerian scored a hat-trick in the 2024 UEFA Europa League final?", options: ["Ademola Lookman", "Victor Osimhen", "Samuel Chukwueze", "Victor Boniface"], answer: "Ademola Lookman", explanation: "Ademola Lookman scored all three Atalanta goals in the final against Bayer Leverkusen.", source: "https://www.uefa.com/uefaeuropaleague/news/028d-1af3e68c4bc9-25496f3a5775-1000--atalanta-3-0-leverkusen-lookman-hat-trick-secures-first-eur/" },
  { year: 2025, category: "Television", subcategory: "Reality TV", difficulty: "MEDIUM", question: "How many seasons had BBNaija reached with its July 2025 premiere?", options: ["10", "8", "9", "11"], answer: "10", explanation: "The 2025 edition was promoted as BBNaija Season 10.", source: "https://www.dstv.com/africamagic/en-ng/show/big-brother-naija/season/10/faqs" },
  { year: 2026, category: "Television", subcategory: "Reality TV", difficulty: "MEDIUM", question: "What total grand-prize value was announced for BBNaija Season 11 in 2026?", options: ["₦160 million", "₦100 million", "₦150 million", "₦200 million"], answer: "₦160 million", explanation: "Africa Magic announced a record ₦160 million total grand prize for Season 11.", source: "https://www.dstv.com/africamagic/show/big-brother-naija" },
  { year: 2021, category: "Music", subcategory: "Awards", difficulty: "HARD", question: "What was the Grammy category won by Burna Boy's Twice As Tall?", options: ["Best Global Music Album", "Album of the Year", "Best African Music Performance", "Best Reggae Album"], answer: "Best Global Music Album", explanation: "The renamed Best Global Music Album category was won by Twice As Tall.", source: "https://www.grammy.com/news/2021-grammys-complete-winners-nominees-list/" },
  { year: 2006, category: "Television", subcategory: "Reality TV", difficulty: "HARD", question: "Which future BBNaija host was a housemate in the original 2006 edition?", options: ["Ebuka Obi-Uchendu", "IK Osakioduwa", "Toke Makinwa", "Uti Nwachukwu"], answer: "Ebuka Obi-Uchendu", explanation: "Ebuka was a housemate in the first Big Brother Nigeria and later became the show's long-running host.", source: "https://www.dstv.com/africamagic/en-ng/show/big-brother-naija/season/10/faqs" },
  { year: 2013, category: "Sports", subcategory: "AFCON", difficulty: "MEDIUM", question: "Which country did Nigeria beat in the 2013 AFCON final?", options: ["Burkina Faso", "Ghana", "Côte d'Ivoire", "Mali"], answer: "Burkina Faso", explanation: "Nigeria beat Burkina Faso 1–0 to claim its third AFCON title.", source: "https://www.cafonline.com/caf-africa-cup-of-nations/news/nigeria-crowned-african-champions/" }
];
async function main() { for (const item of seeds) { const fingerprint = crypto.createHash("sha256").update(item.question.trim().toLowerCase()).digest("hex"); await db.question.upsert({ where: { fingerprint }, update: {}, create: { question: item.question, year: item.year, category: item.category, subcategory: item.subcategory, difficulty: item.difficulty, questionType: item.type ?? "MULTIPLE_CHOICE", options: item.options, correctAnswer: item.answer, explanation: item.explanation, source: item.source, fingerprint, status: QuestionStatus.PUBLISHED, verified: true, publishedAt: new Date() } }); } console.log(`Seeded ${seeds.length} sourced FLASHBACK questions.`); }
main().finally(() => db.$disconnect());
