"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Copy, Share2, Swords, Trophy } from "lucide-react";
import { PlayGame, type Round } from "@/components/play-game";
import { presenters, type PresenterId } from "@/lib/presenters";
type Challenge = { code: string; creatorName: string; scoreToBeat: number; nostalgiaToBeat: number; bestOf: number; leaderboard: { rank: number; playerName: string; score: number; nostalgia: number; attempts: number; creator: boolean }[] };
export function ChallengeExperience({ code }: { code: string }) {
  const [challenge, setChallenge] = useState<Challenge | null>(null), [round, setRound] = useState<Round | null>(null), [name, setName] = useState(""), [presenter, setPresenter] = useState<PresenterId>("LAGOS_HYPE"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(() => fetch(`/api/challenges/${code}`, { cache: "no-store" }).then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setChallenge(data); }).catch((reason) => setError(reason.message)), [code]);
  useEffect(() => { load(); }, [load]);
  async function start(): Promise<Round> { setBusy(true); setError(""); let key = localStorage.getItem("flashback_challenger_key"); if (!key) { key = crypto.randomUUID(); localStorage.setItem("flashback_challenger_key", key); } const response = await fetch(`/api/challenges/${code}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ playerName: name || "Naija Historian", playerKey: key, presenter }) }), data = await response.json(); setBusy(false); if (!response.ok) { setError(data.error); throw new Error(data.error); } return data;
  }
  async function submit(event: FormEvent) { event.preventDefault(); try { setRound(await start()); } catch { /* the visible error is already set */ } }
  async function share() { const data = { title: "FLASHBACK Naija Challenge", text: `${challenge?.creatorName} says you cannot beat ${challenge?.scoreToBeat.toLocaleString()} points. Oya prove them wrong!`, url: location.href }; if (navigator.share) await navigator.share(data); else await navigator.clipboard.writeText(location.href); }
  if (round) return <PlayGame key={round.gameId} mode="quick" initialRound={round} challengeCode={code} restartChallenge={start} />;
  if (error && !challenge) return <main className="game-page"><section className="empty-game"><span>CHALLENGE UPDATE</span><h1>{error}</h1></section></main>;
  if (!challenge) return <main className="game-page">Opening the challenge…</main>;
  return <main className="challenge-page"><section className="challenge-hero"><Swords /><span>BEAT MY FLASHBACK</span><h1>{challenge.creatorName}<br />SCORED <em>{challenge.scoreToBeat.toLocaleString()}</em>.</h1><p>You get the exact same ten questions and three attempts. Only your best score stays on the table.</p><div><button onClick={share}><Share2 />SHARE</button><button onClick={() => navigator.clipboard.writeText(location.href)}><Copy />COPY LINK</button></div></section><section className="challenge-layout"><form onSubmit={submit}><span>YOUR TURN</span><h2>YOU FIT BEAT AM?</h2><label>PLAYER NAME<input value={name} onChange={(event) => setName(event.target.value)} minLength={2} maxLength={24} required placeholder="Your name" /></label><b>CHOOSE YOUR HOST</b><div className="challenge-hosts">{Object.entries(presenters).map(([id, host]) => <button type="button" key={id} className={presenter === id ? "active" : ""} onClick={() => setPresenter(id as PresenterId)}><i>{host.emoji}</i><span>{host.name}</span></button>)}</div>{error && <div className="form-error">{error}</div>}<button className="cta" disabled={busy}>{busy ? "SETTING QUESTIONS…" : `START ATTEMPT · BEST OF ${challenge.bestOf}`}</button></form><div className="challenge-table"><div><Trophy /><span>MINI LEADERBOARD</span></div>{challenge.leaderboard.map((row) => <article key={`${row.playerName}-${row.creator}`}><b>#{row.rank}</b><div><strong>{row.playerName}</strong><small>{row.creator ? "CHALLENGE CREATOR" : `${row.attempts}/${challenge.bestOf} ATTEMPTS`}</small></div><em>{row.score.toLocaleString()}</em><span>{row.nostalgia}%</span></article>)}</div></section></main>;
}
