"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Check, Clock3, Copy, RotateCcw, Share2, Swords, X, Zap } from "lucide-react";
import { presenterLine, presenters, type PresenterId } from "@/lib/presenters";
type Q = { id: string; year: number; category: string; difficulty: string; question: string; options: string[] };
export type Round = { gameId: string; token: string; presenter: PresenterId; seconds: number; attempt?: number; questions: Q[] };
type Result = { score: number; correct: number; nostalgia: number; breakdown: Record<string, { correct: number; total: number }>; identity?: { title: string; emoji: string; level: string } | null };
type Feedback = { correct: boolean; correctAnswer: string; explanation: string; points: number; choice: string | null };
export function PlayGame({ mode, year, decade, category, presenter = "LAGOS_HYPE", initialRound, challengeCode, restartChallenge }: { mode: string; year?: number; decade?: number; category?: string; presenter?: PresenterId; initialRound?: Round; challengeCode?: string; restartChallenge?: () => Promise<Round> }) {
  const [round, setRound] = useState<Round | null>(initialRound ?? null), [index, setIndex] = useState(0), [seconds, setSeconds] = useState(initialRound?.seconds ?? 60), [score, setScore] = useState(0), [feedback, setFeedback] = useState<Feedback | null>(null), [result, setResult] = useState<Result | null>(null), [error, setError] = useState("");
  const [createdCode, setCreatedCode] = useState(""), [creatorName, setCreatorName] = useState(""), [sharing, setSharing] = useState(false);
  const started = useRef(Date.now()), locked = useRef(false);
  async function begin() { setError(""); setRound(null); setResult(null); setFeedback(null); setCreatedCode(""); setIndex(0); setScore(0); locked.current = false; try { if (restartChallenge) { const next = await restartChallenge(); setRound(next); setSeconds(next.seconds); started.current = Date.now(); return; } const response = await fetch("/api/games", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode: mode.toUpperCase(), year, decade, category, presenter }) }); const data = await response.json(); if (!response.ok) return setError(data.error); setRound(data); setSeconds(data.seconds); started.current = Date.now(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Network wahala. Try the round again."); } }
  useEffect(() => { if (!initialRound) void begin(); }, []);
  useEffect(() => { if (!round || result) return; const timer = window.setInterval(() => setSeconds((value) => { if (value <= 1) { window.clearInterval(timer); void answer(null); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [round, result]);
  async function answer(choice: string | null) { if (!round || locked.current || result) return; locked.current = true; const response = await fetch(`/api/games/${round.gameId}/answer`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token: round.token, position: index, answer: choice, responseMs: Date.now() - started.current }) }); const data = await response.json(); if (!response.ok) { locked.current = false; setError(data.error); return; } setFeedback({ ...data, choice }); setScore(data.score); window.setTimeout(() => { if (data.finished) setResult(data.result); else { setIndex((value) => value + 1); started.current = Date.now(); setFeedback(null); locked.current = false; } }, 1200); }
  async function makeChallenge() { if (!round || !result) return; setSharing(true); const response = await fetch("/api/challenges", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ gameId: round.gameId, token: round.token, creatorName: creatorName || undefined }) }), data = await response.json(); setSharing(false); if (!response.ok) return setError(data.error); setCreatedCode(data.code); }
  async function shareChallenge() { const url = `${location.origin}/challenge/${createdCode}`, data = { title: "FLASHBACK Naija Challenge", text: `I scored ${result?.score.toLocaleString()} on FLASHBACK 🇳🇬. Oya beat my score!`, url }; if (navigator.share) await navigator.share(data); else await navigator.clipboard.writeText(url); }
  if (error) return <main className="game-page"><section className="empty-game"><span>SMALL HOLD-UP</span><h1>{error}</h1><button className="cta" onClick={begin}>TRY AGAIN</button></section></main>;
  if (!round) return <main className="game-page"><p>Loading memories…</p></main>;
  const host = presenters[round.presenter] ?? presenters.LAGOS_HYPE;
  if (result) return <main className="game-page"><section className="game-result"><div className="result-host"><i>{host.emoji}</i><span>{host.name} · {host.title}</span></div><span>YOUR FLASHBACK</span><strong>{result.nostalgia}%</strong><h1>NAIJA NOSTALGIA</h1><p>{presenterLine(round.presenter, result.nostalgia >= 70 ? "correct" : "wrong", index)}</p>{result.identity && <div className="earned-identity"><i>{result.identity.emoji}</i><div><small>YOUR IDENTITY</small><b>{result.identity.level} {result.identity.title}</b></div></div>}<div className="result-numbers"><div><b>{result.score.toLocaleString()}</b><small>POINTS</small></div><div><b>{result.correct}/10</b><small>CORRECT</small></div></div>{challengeCode ? <div className="challenge-finished"><Swords /><b>ATTEMPT {round.attempt ?? 1} COMPLETE</b><p>Your score is now on this challenge’s mini-table.</p><Link className="cta" href={`/challenge/${challengeCode}`}>VIEW CHALLENGE TABLE</Link></div> : createdCode ? <div className="challenge-created"><span>YOUR CHALLENGE IS LIVE</span><b>{createdCode}</b><button className="cta" onClick={shareChallenge}><Share2 />SHARE “BEAT MY SCORE”</button><button className="ghost" onClick={() => navigator.clipboard.writeText(`${location.origin}/challenge/${createdCode}`)}><Copy />COPY LINK</button></div> : <div className="challenge-maker"><Swords /><div><b>THINK YOUR SCORE IS SAFE?</b><span>Give your friends these exact ten questions.</span></div><input value={creatorName} onChange={(event) => setCreatorName(event.target.value)} maxLength={24} placeholder="Your name (if playing as guest)" /><button onClick={makeChallenge} disabled={sharing}>{sharing ? "CREATING…" : `CHALLENGE FRIENDS TO BEAT ${result.score.toLocaleString()}`}</button></div>}<div className="result-actions"><button className="cta" onClick={begin}><RotateCcw />{challengeCode ? "NEXT ATTEMPT" : "PLAY AGAIN"}</button><Link className="ghost" href="/play">CHANGE MODE</Link></div></section></main>;
  const q = round.questions[index]!;
  const state = feedback?.correct ? "correct" : feedback?.choice === null ? "timeout" : "wrong";
  return <main className="game-page"><div className="presenter-chip"><i>{host.emoji}</i><div><b>{host.name}</b><span>{host.title}</span></div></div><header className="game-hud"><div><span>QUESTION</span><b>{index + 1}/10</b></div><div className="game-progress"><i style={{ width: `${index * 10}%` }} /></div><div><Clock3 /><b>{seconds}s</b></div><div><Zap /><b>{score}</b></div></header><section className="question"><div className="question-meta"><strong>{q.year}</strong><span>{q.category}</span><b>{q.difficulty}</b></div><h1>{q.question}</h1><div className="options">{q.options.map((choice, n) => <button disabled={!!feedback} key={choice} onClick={() => answer(choice)} className={feedback ? choice === feedback.correctAnswer ? "correct" : choice === feedback.choice ? "wrong" : "dim" : ""}><i>{String.fromCharCode(65 + n)}</i><span>{choice}</span>{feedback && choice === feedback.correctAnswer ? <Check /> : feedback?.choice === choice ? <X /> : null}</button>)}</div>{feedback && <div className={feedback.correct ? "answer-note good" : "answer-note bad"}><div className="host-reaction"><i>{host.emoji}</i><b>{presenterLine(round.presenter, state, index)}</b></div><span>{feedback.explanation}</span></div>}</section></main>;
}
