"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Check, Clock3, RotateCcw, X, Zap } from "lucide-react";
type Q = { id: string; year: number; category: string; difficulty: string; question: string; options: string[] };
type Round = { gameId: string; token: string; seconds: number; questions: Q[] };
type Result = { score: number; correct: number; nostalgia: number; breakdown: Record<string, { correct: number; total: number }> };
export function PlayGame({ mode, year, decade, category }: { mode: string; year?: number; decade?: number; category?: string }) {
  const [round, setRound] = useState<Round | null>(null), [index, setIndex] = useState(0), [seconds, setSeconds] = useState(60), [score, setScore] = useState(0), [feedback, setFeedback] = useState<any>(null), [result, setResult] = useState<Result | null>(null), [error, setError] = useState("");
  const started = useRef(Date.now()), locked = useRef(false);
  async function begin() { setError(""); setRound(null); setResult(null); setIndex(0); setScore(0); const response = await fetch("/api/games", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ mode: mode.toUpperCase(), year, decade, category }) }); const data = await response.json(); if (!response.ok) return setError(data.error); setRound(data); setSeconds(data.seconds); started.current = Date.now(); }
  useEffect(() => { begin(); }, []);
  useEffect(() => { if (!round || result) return; const timer = window.setInterval(() => setSeconds((value) => { if (value <= 1) { window.clearInterval(timer); void answer(null); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [round, result]);
  async function answer(choice: string | null) { if (!round || locked.current || result) return; locked.current = true; const response = await fetch(`/api/games/${round.gameId}/answer`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token: round.token, position: index, answer: choice, responseMs: Date.now() - started.current }) }); const data = await response.json(); if (!response.ok) { setError(data.error); return; } setFeedback({ ...data, choice }); setScore(data.score); window.setTimeout(() => { if (data.finished) setResult(data.result); else { setIndex((value) => value + 1); started.current = Date.now(); setFeedback(null); locked.current = false; } }, 1100); }
  if (error) return <main className="game-page"><section className="empty-game"><span>SMALL HOLD-UP</span><h1>{error}</h1><button className="cta" onClick={begin}>TRY AGAIN</button></section></main>;
  if (!round) return <main className="game-page"><p>Loading memories…</p></main>;
  if (result) return <main className="game-page"><section className="game-result"><span>YOUR FLASHBACK</span><strong>{result.nostalgia}%</strong><h1>NAIJA NOSTALGIA</h1><p>{result.nostalgia >= 85 ? "Omo! You definitely remember the old days." : result.nostalgia >= 60 ? "You remember well, but some memories don fade small." : "Time to call the group chat for backup."}</p><div className="result-numbers"><div><b>{result.score}</b><small>POINTS</small></div><div><b>{result.correct}/10</b><small>CORRECT</small></div></div><div className="result-actions"><button className="cta" onClick={begin}><RotateCcw />PLAY AGAIN</button><Link className="ghost" href="/play">CHANGE MODE</Link></div></section></main>;
  const q = round.questions[index]!;
  return <main className="game-page"><header className="game-hud"><div><span>QUESTION</span><b>{index + 1}/10</b></div><div className="game-progress"><i style={{ width: `${index * 10}%` }} /></div><div><Clock3 /><b>{seconds}s</b></div><div><Zap /><b>{score}</b></div></header><section className="question"><div className="question-meta"><strong>{q.year}</strong><span>{q.category}</span><b>{q.difficulty}</b></div><h1>{q.question}</h1><div className="options">{q.options.map((choice, n) => <button disabled={!!feedback} key={choice} onClick={() => answer(choice)} className={feedback ? choice === feedback.correctAnswer ? "correct" : choice === feedback.choice ? "wrong" : "dim" : ""}><i>{String.fromCharCode(65 + n)}</i><span>{choice}</span>{feedback && choice === feedback.correctAnswer ? <Check /> : feedback?.choice === choice ? <X /> : null}</button>)}</div>{feedback && <div className={feedback.correct ? "answer-note good" : "answer-note bad"}><b>{feedback.correct ? `CORRECT! +${feedback.points}` : `NAH — ${feedback.correctAnswer}`}</b><span>{feedback.explanation}</span></div>}</section></main>;
}
