import crypto from "node:crypto";
import { readFile } from "node:fs/promises";
import { z } from "zod";
import { db } from "../lib/db";
const schema = z.array(z.object({ externalId: z.string().optional(), question: z.string().trim().min(10), year: z.number().int().min(2000).max(new Date().getFullYear()), category: z.string().trim().min(2), subcategory: z.string().trim().min(2), difficulty: z.enum(["EASY", "MEDIUM", "HARD", "EXPERT"]), questionType: z.enum(["MULTIPLE_CHOICE", "TRUE_FALSE", "IMAGE", "AUDIO", "LOGO", "FINISH_IT", "TIMELINE", "GUESS_PERSON", "GUESS_YEAR", "PRICE_MEMORY"]), options: z.array(z.string().trim().min(1)).min(2).max(6), correctAnswer: z.string().trim().min(1), explanation: z.string().trim().min(5), source: z.string().url(), imageUrl: z.string().url().nullable().optional(), audioUrl: z.string().url().nullable().optional() }));
async function main() { const path = process.argv[2]; if (!path) throw new Error("Usage: npm run data:import -- questions.json"); const parsed = schema.safeParse(JSON.parse(await readFile(path, "utf8"))); if (!parsed.success) throw new Error(`Import rejected:\n${parsed.error.message}`); const normalized = parsed.data.map((q) => ({ ...q, fingerprint: crypto.createHash("sha256").update(q.question.toLowerCase().replace(/\W/g, "")).digest("hex") })); const fingerprints = new Set<string>(); for (const q of normalized) { if (!q.options.includes(q.correctAnswer)) throw new Error(`Correct answer is not an option: ${q.question}`); if (new Set(q.options.map((o) => o.toLowerCase())).size !== q.options.length) throw new Error(`Duplicate options: ${q.question}`); if (fingerprints.has(q.fingerprint)) throw new Error(`Duplicate wording inside import: ${q.question}`); fingerprints.add(q.fingerprint); }
  const existing = await db.question.findMany({ where: { fingerprint: { in: [...fingerprints] } }, select: { fingerprint: true } }); if (existing.length) throw new Error(`${existing.length} question(s) duplicate existing database records.`);
  await db.question.createMany({ data: normalized.map((q) => ({ ...q, imageUrl: q.imageUrl ?? null, audioUrl: q.audioUrl ?? null, status: "DRAFT", verified: false })) }); console.log(`Imported ${normalized.length} questions as DRAFT. Review and verify them in /admin before publishing.`); }
main().finally(() => db.$disconnect());
